//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string Articul { get; set; }
        public decimal MinimalCost { get; set; }
        public int ProductTypeId { get; set; }
        public int WorkersCount { get; set; }
        public int WorkShopId { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual WorkShop WorkShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
